version: 2
registries:
  rubygems-server-rubygems-pkg-github-com-vnda:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/vnda
    username: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_VNDA_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_VNDA_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: rails
    versions:
    - "> 4.2.11.1"
  - dependency-name: honeybadger
    versions:
    - 4.7.2
    - 4.7.3
  rebase-strategy: disabled
  registries:
  - rubygems-server-rubygems-pkg-github-com-vnda
